"""
Create a program that will play the 'Cows and bulls' game with the user.
The game works like this:

Radomly generate a 4 digit number. Ask the user to guess a 4-digit number.
For every digit that the user guessed correctly in the correct place,
they have a 'cow'. For every digit the user guessed correctly in the wrong place
is a 'bull'. Every time the user makes a guess, tell them how many 'cows' and 'bulls'
they have. Once the user guesses the correct number, the game is over.
Keep track of the number of guesses the user makes throughout the game and tell the user at the end.

Say the number generated by computer is 1038. An example interaction
could look like this:

Welcome to the Cows and Bulls Game!
Enter a number:
>>> 1234
2 cows, 0 bulls
>>> 1256
1 cow, 1 bull
...
"""

from random import sample

def choosen():
    num_list = ['1','2','3','4','5','6','7','8','9','0']
    sampled_list = sample(num_list, 4)
#    sampled_list = ''.join(sampled_list)
    return sampled_list

def change_var_to_int_list(int_value_user):
    str_int_list_user = list(str(int_value_user))
#    int_list_user = list(map(int, str_intlist_user))
    return str_int_list_user

def cow_or_bull(user_value, sample_value):
    cow = 0
    bull = 0
    for i in range(4):
        if user_value[i] in sample_value:
            if user_value[i] == sample_value[i]:
                cow += 1
            else:
                bull += 1
    return [cow, bull]

def change_to_int(str_list):
    string = ''.join(str_list)
    return int(string)

def cow_or_cows(result):
    if result[0] == 1:
        return "Cow"
    else:
        return "Cows"

def bull_or_bulls(result):
    if result[1] == 1:
        return "Bull"
    else:
        return "Bulls"
''' First write a code
if __name__=='__main__':
    order_value = choosen()

    user_input_value = input("Guess a number\n")
    user_input_value = change_var_to_int_list(user_input_value)
    while user_input_value != order_value:
        result = cow_or_bull(user_input_value, order_value)
        cow = cow_or_cows(result)
        bull = bull_or_bulls(result)
        print(f'{cow} = {result[0]} , {bull} = {result[1]}')
        user_input_value = input("Guess a number\n")
        if user_input_value == 'exit':
            break
        user_input_value = change_var_to_int_list(user_input_value)

    print("End Game")
'''
''' From Practice Python
import random

def compare_numbers(number, user_guess):
    cowbull = [0,0] #cows, then bulls
    for i in range(len(number)):
        if number[i] == user_guess[i]:
            cowbull[1]+=1
        else:
            cowbull[0]+=1
    return cowbull

if __name__=="__main__":
    playing = True #gotta play the game
    number = str(random.randint(0,9999)) #random 4 digit number
    guesses = 0

    print("Let's play a game of Cowbull!") #explanation
    print("I will generate a number, and you have to guess the numbers one digit at a time.")
    print("For every number in the wrong place, you get a cow. For every one in the right place, you get a bull.")
    print("The game ends when you get 4 bulls!")
    print("Type exit at any prompt to exit.")

    while playing:
        user_guess = input("Give me your best guess!")
        if user_guess == "exit":
            break
        cowbullcount = compare_numbers(number,user_guess)
        guesses+=1

        print("You have "+ str(cowbullcount[0]) + " cows, and " + str(cowbullcount[1]) + " bulls.")

        if cowbullcount[1]==4:
            playing = False
            print("You win the game after " + str(guesses) + "! The number was "+str(number))
            break #redundant exit
        else:
            print("Your guess isn't quite right, try again.")
'''
# modernization first my code
if __name__=='__main__':
    order_value = choosen()
    playing = True
    while playing:
        user_input_value = input("Guess a number\n")
        if user_input_value == 'exit':
            break
        user_input_value = change_var_to_int_list(user_input_value)
        result = cow_or_bull(user_input_value, order_value)

        cow = cow_or_cows(result)
        bull = bull_or_bulls(result)
        print(f'{cow} = {result[0]} , {bull} = {result[1]}')
        if result[1] == 4:
            playing = False

    print("End Game")
